(function () {
  'use strict';
  var S = GamePicker.storage, state = null, moduleKey = 'play', installPrompt = null;
  var selected = { play: [], chat: [], outing: [] }, outingRegion = '全部', current = null, busy = false;
  function $(id) { return document.getElementById(id); }
  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) { return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]; }); }
  function save() { S.saveState(state); }
  function mod(k) { return state.modules[k]; }
  function cat(m, id) { return m.categories.find(function (c) { return c.id === id; }) || m.categories[0]; }
  function itemName(a) { return state.settings.language === 'en-US' ? (a.nameEn || a.nameZh) : (a.nameZh || a.nameEn); }
  function isEn(){ return state && state.settings.language === 'en-US'; }
  function tr(zh,en){ return isEn() ? en : zh; }
  function applyLanguage(){
    var en=isEn(); document.documentElement.lang=en?'en':'zh-CN'; document.title=en?'ExploreKids · Family Weekend':'探索派 · 亲子周末';
    var slogan=document.querySelector('.brand-slogan'); if(slogan)slogan.textContent=tr('一起玩，一起聊，周末去探索','Play together, chat together, explore the weekend');
    var nav=document.querySelectorAll('.tab'); if(nav.length){nav[0].textContent='🧸 '+tr('玩一玩','Play');nav[1].textContent='💬 '+tr('聊聊天','Chat');nav[2].textContent='🧭 '+tr('去哪里','Go out');}
    $('open-settings').title=tr('设置','Settings'); $('open-settings').setAttribute('aria-label',tr('设置','Settings'));
    document.querySelector('#view-play h1').textContent=tr('现在玩什么？','What shall we play?'); document.querySelector('#view-play .subtitle').textContent=tr('点一下，让探索派帮你挑一个亲子活动～','Tap once and let ExploreKids pick a family activity.');
    document.querySelector('#view-chat h1').textContent=tr('我们聊点什么呢？','What shall we talk about?'); document.querySelector('#view-chat .subtitle').textContent=tr('没有标准答案，认真听彼此说就很好～','There is no perfect answer—listening is what matters.');
    document.querySelector('#view-outing h1').textContent=tr('周末去哪里？','Where shall we go this weekend?'); document.querySelector('#view-outing .subtitle').textContent=tr('先从深圳市内和周边，挑一个轻松去处～','Pick an easy family destination in Shenzhen or nearby.');
    document.querySelector('#play-pick .hero-btn-main').textContent=tr('开始','Start'); document.querySelector('#play-pick .hero-btn-sub').textContent=tr('点我抽一个','Pick one');
    document.querySelector('#outing-pick .hero-btn-main').textContent=tr('出发','Go'); document.querySelector('#outing-pick .hero-btn-sub').textContent=tr('帮我选个地方','Pick a place');
    $('chat-pick').innerHTML='<span class="chat-pick-emoji">🎴</span>'+tr('抽一张聊天卡','Draw a chat card'); $('chat-reroll').textContent='🔄 '+tr('换一个','Another one'); $('chat-answer').textContent='💡 '+tr('查看答案','Show answer');
    document.querySelectorAll('.manage-trigger').forEach(function(b){b.textContent='📦 '+tr('管理','Manage');});
    var pf=document.querySelector('[data-toggle="play-filter"]'), cf=$('chat-filter-toggle'), of=$('outing-filter-toggle'); if(pf)pf.innerHTML='🎛️ <span>'+tr('筛选','Filter')+'</span><span class="filter-summary" id="play-summary"></span>'; if(cf)cf.innerHTML='🎯 <span>'+tr('选择话题','Topics')+'</span><span class="filter-summary" id="chat-selected"></span>'; if(of)of.innerHTML='🎛️ <span>'+tr('筛选','Filter')+'</span><span class="filter-summary" id="outing-summary"></span>'; updateSummaries();
    $('drawer-close').setAttribute('aria-label',tr('关闭','Close')); document.querySelector('#settings-modal h2').textContent='⚙️ '+tr('设置','Settings'); document.querySelector('#settings-modal .field').firstChild.textContent=tr('我的名字','Your name'); document.querySelectorAll('#settings-modal .field')[1].firstChild.textContent=tr('语言','Language');
    document.querySelector('#install-note').textContent=tr('安装后可像普通 APP 一样从桌面打开探索派。','Install ExploreKids and open it from your home screen like a regular app.');
    document.querySelectorAll('#settings-modal details')[0].querySelector('summary').textContent='iPhone / iPad Safari'; document.querySelectorAll('#settings-modal details')[1].querySelector('summary').textContent='Android Chrome';
    var steps= document.querySelectorAll('#settings-modal details ol'); if(en){steps[0].innerHTML='<li>Open ExploreKids in Safari</li><li>Tap the Share button</li><li>Choose “Add to Home Screen”</li>';steps[1].innerHTML='<li>Open ExploreKids in Chrome</li><li>Tap the menu</li><li>Choose “Install app” or “Add to Home screen”</li>';}
    var indoor=$('outing-indoor'), duration=$('outing-duration'); if(indoor){indoor.options[0].text=tr('室内/室外不限','Indoor / outdoor');indoor.options[1].text=tr('室内','Indoor');indoor.options[2].text=tr('室外','Outdoor');} if(duration){duration.options[0].text=tr('时长不限','Any duration');duration.options[1].text=tr('2小时左右','About 2 hours');duration.options[2].text=tr('半天','Half day');duration.options[3].text=tr('一天','Full day');duration.options[4].text=tr('1–2天','1–2 days');}
    renderCategories('play','play-categories'); renderCategories('chat','chat-categories'); renderOutingFilters(); updateSummaries();
  }
  function pick(list) { return list[Math.floor(Math.random() * list.length)]; }
  function iconMarkup(a) { var map={'磁力片':'building-blocks.svg','拼图':'three-little-pigs.svg','绘本':'literacy.svg','英语':'english-learning.svg','蹦床':'trampoline.svg','引体':'pull-up-bar.svg','仰卧':'sit-ups.svg','纸盘':'paper-airplane.svg'}; var key=Object.keys(map).find(function(k){return (a.nameZh||'').indexOf(k)>=0;}); return key ? '<img class="activity-icon-svg" src="assets/icons/'+map[key]+'" alt="">' : esc(a.emoji||'🎈'); }
  function burst(kind) { if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)return; var layer=$('confetti-layer'); if(!layer)return; var icons=kind==='chat'?['✦','✧','💜']:kind==='outing'?['➜','✦','🧭']:['●','✦','★','🎈']; for(var i=0;i<14;i++){var s=document.createElement('span');s.className='fx-particle fx-'+kind;s.textContent=icons[i%icons.length];s.style.left=(35+Math.random()*30)+'%';s.style.top=(30+Math.random()*18)+'%';s.style.setProperty('--dx',((Math.random()-.5)*180)+'px');s.style.setProperty('--dy',((Math.random()-.5)*180)+'px');layer.appendChild(s);setTimeout(function(){s.remove();},900);}}
  function showView(v) { document.querySelectorAll('.view').forEach(function (x) { x.classList.toggle('active', x.id === 'view-' + v); }); document.querySelectorAll('.tab').forEach(function (x) { x.classList.toggle('active', x.dataset.view === v); }); document.body.dataset.module=v; moduleKey = v; }
  function renderCategories(k, id) { var m = mod(k), box = $(id); if (!box) return; box.innerHTML = ''; m.categories.forEach(function (c) { var b = document.createElement('button'); b.type = 'button'; b.className = 'clay-chip' + (selected[k].indexOf(c.id) >= 0 ? ' active' : ''); b.textContent = c.emoji + ' ' + (isEn() ? c.nameEn : c.nameZh); b.onclick = function () { var i = selected[k].indexOf(c.id); if (i >= 0) selected[k].splice(i, 1); else selected[k].push(c.id); renderCategories(k, id); updateSummaries(); }; box.appendChild(b); }); }
  function updateSummaries() { $('play-summary').textContent = selected.play.length ? selected.play.length + ' '+tr('个分类','categories') : tr('全部','All'); $('chat-selected').textContent = selected.chat.length ? selected.chat.length + ' '+tr('个分类','categories') : tr('全部','All'); $('outing-summary').textContent = outingRegion === '全部' ? tr('全部','All') : (isEn()?({深圳市内:'Shenzhen',深圳周边:'Nearby Shenzhen'}[outingRegion]||outingRegion):outingRegion); }
  function animateResult(el, cls, done) { el.hidden = false; el.classList.remove(cls); void el.offsetWidth; el.classList.add(cls); setTimeout(done, 620); }
  function playPick() { if (busy) return; var m = mod('play'), pool = m.items.filter(function (a) { return !selected.play.length || selected.play.indexOf(a.categoryId) >= 0; }); if (!pool.length) return; busy = true; var box = $('play-result'), i = 0; box.hidden = false; box.innerHTML = '<div class="result-card play-result-card"><div class="result-emoji clay-orb" id="play-result-emoji">🎲</div><h2 id="play-result-name">'+tr('正在选择…','Choosing…')+'</h2></div>'; var timer = setInterval(function () { var a = pool[i++ % pool.length]; $('play-result-emoji').textContent = a.emoji || '🎈'; $('play-result-name').textContent = itemName(a); }, 70); setTimeout(function () { clearInterval(timer); var a = pick(pool); a.lastPickedAt = S.now(); a.pickCount = (a.pickCount || 0) + 1; m.lastPickedId = a.id; save(); box.innerHTML = '<div class="result-card play-result-card result-jelly"><div class="result-emoji clay-orb">' + iconMarkup(a) + '</div><h2>' + esc(itemName(a)) + '</h2><p class="result-desc">' + esc(isEn()?(a.descriptionEn||a.descriptionZh||''):(a.descriptionZh || '')) + '</p><div class="result-actions"><button class="clay-btn primary" id="play-again">🔄 '+tr('换一个','Another one')+'</button></div></div>'; $('play-again').onclick = playPick; burst('play'); busy = false; }, 700); }
  function chatPick() {
    if (busy) return;
    var m = mod('chat'), pool = m.items.filter(function (a) { return !selected.chat.length || selected.chat.indexOf(a.categoryId) >= 0; });
    if (!pool.length) return;
    busy = true;
    var button = $('chat-pick'), card = $('chat-card'), a = pick(pool);
    button.disabled = true; button.classList.remove('is-dealing'); void button.offsetWidth; button.classList.add('is-dealing');
    card.hidden = false; card.classList.remove('is-dealing'); void card.offsetWidth; card.classList.add('is-dealing');
    var en = isEn(), c = cat(m, a.categoryId);
    $('chat-emoji').textContent = a.emoji || '💬'; $('chat-badge').textContent = c ? c.emoji + ' ' + (en ? c.nameEn : c.nameZh) : '';
    $('chat-prompt').textContent = en ? (a.promptEn || a.descriptionEn || a.nameEn) : (a.promptZh || a.descriptionZh || a.nameZh);
    $('chat-followups').innerHTML = ''; $('chat-fact').hidden = true; $('chat-answer').hidden = true;
    var follow = en ? (a.followUpsEn || a.followUpsZh || []) : (a.followUpsZh || []), fact = en ? (a.factEn || '') : (a.factZh || ''), answer = en ? (a.answerEn || '') : (a.answerZh || '');
    setTimeout(function(){ $('chat-followups').innerHTML = follow.map(function(x){ return '<span class="chat-followup">'+esc(x)+'</span>'; }).join(''); $('chat-followups').classList.add('chat-segment-in'); }, 120);
    setTimeout(function(){ $('chat-fact').textContent = fact; $('chat-fact').hidden = !fact; if(fact)$('chat-fact').classList.add('chat-segment-in'); $('chat-answer').hidden = !answer; $('chat-answer').onclick = function(){ window.alert(answer); }; }, 250);
    m.lastPickedId = a.id; a.lastPickedAt = S.now(); a.pickCount = (a.pickCount || 0) + 1; save(); burst('chat');
    setTimeout(function(){ button.disabled = false; button.classList.remove('is-dealing'); busy = false; }, 620);
  }
  function renderOutingFilters() { var m = mod('outing'); var r = $('outing-region'); r.innerHTML = ''; ['全部','深圳市内','深圳周边'].forEach(function (x) { var b = document.createElement('button'); b.className = 'clay-chip' + (outingRegion === x ? ' active' : ''); b.textContent = isEn()?({全部:'All',深圳市内:'Shenzhen',深圳周边:'Nearby'}[x]):x; b.onclick = function () { outingRegion = x; renderOutingFilters(); updateSummaries(); }; r.appendChild(b); }); renderCategories('outing', 'outing-categories'); updateSummaries(); }
  function outingPick() { if (busy) return; var m = mod('outing'), io = $('outing-indoor').value, dur = $('outing-duration').value, pool = m.items.filter(function (a) { return (outingRegion === '全部' || a.region === outingRegion) && (!selected.outing.length || selected.outing.indexOf(a.categoryId) >= 0) && (!io || String(a.indoorOutdoor || '').indexOf(io) >= 0) && (!dur || String(a.duration || '').indexOf(dur) >= 0); }); if (!pool.length) return; busy = true; var a = pick(pool), box = $('outing-result'), en = isEn(); box.hidden = false; box.innerHTML = '<div class="result-card outing-card outing-result-in"><div class="outing-route-icon compass-spin">✦</div><h2>' + esc(en?(a.nameEn||a.nameZh):a.nameZh) + '</h2><div class="result-meta"><span class="badge">' + esc(en?({深圳市内:'Shenzhen',深圳周边:'Nearby Shenzhen'}[a.region]||a.region):a.region) + '</span><span class="badge">' + esc(a.area) + '</span></div><p class="result-desc">' + esc(en?(a.descriptionEn||a.highlights||''):(a.highlights || a.descriptionZh || '')) + '</p><p class="result-materials">' + esc(en?({室内:'Indoor',室外:'Outdoor','室内/室外':'Indoor / outdoor'}[a.indoorOutdoor]||a.indoorOutdoor||''):a.indoorOutdoor || '') + ' · ' + esc(en?({半天:'Half day',一天:'Full day','1–2天':'1–2 days'}[a.duration]||a.duration||''):a.duration || '') + '</p><div class="result-actions outing-actions"><button class="clay-btn primary map-btn">🗺️ ' + tr('地图搜索','Open map') + '</button><button class="clay-btn outing-again">🔄 ' + tr('换一个','Another one') + '</button></div></div>'; m.lastPickedId = a.id; a.lastPickedAt = S.now(); a.pickCount = (a.pickCount || 0) + 1; save(); box.querySelector('.map-btn').onclick = function () { var q=encodeURIComponent(a.mapSearchName || a.nameZh); var ua=navigator.userAgent||''; if(/iPhone|iPad|iPod/i.test(ua)){ window.location.href='maps://?q='+q; } else if(/Android/i.test(ua)){ window.location.href='geo:0,0?q='+q; } else { window.open('https://www.google.com/maps/search/?api=1&query='+q, '_blank'); } }; box.querySelector('.outing-again').onclick = outingPick; burst('outing'); setTimeout(function () { busy = false; }, 720); }
  function renderManager(k) { var m = mod(k), c = $('drawer-content'), list = m.items.slice(); c.innerHTML = '<div class="drawer-tools"><input id="manager-search" class="clay-input" placeholder="🔍 '+tr('搜索本模块内容','Search this library')+'"><button id="manager-add" class="clay-btn small">➕ '+tr('新增','Add')+'</button></div><div class="drawer-count">'+(isEn()?'Total: ':'共 ')+list.length+(isEn()?' items':' 条')+'</div><div class="manager-list">' + list.map(function (a) { var x = cat(m, a.categoryId); return '<div class="manager-item"><div class="manager-main"><div class="manager-icon">' + iconMarkup(a) + '</div><div><h3>' + esc(itemName(a)) + '</h3><span class="badge" style="background:' + esc(x.color) + '">' + esc(x.emoji + ' ' + (isEn()?x.nameEn:x.nameZh)) + '</span><p>' + esc(isEn()?(a.descriptionEn||a.descriptionZh||a.highlights||''):(a.descriptionZh||a.highlights||'')) + '</p></div></div><div class="manager-actions"><button class="icon-btn" data-edit="' + esc(a.id) + '" title="'+tr('编辑','Edit')+'">✏️</button><button class="icon-btn" data-fav="' + esc(a.id) + '" title="'+tr('收藏','Favorite')+'">' + (a.favorite ? '⭐' : '☆') + '</button><button class="icon-btn danger-icon" data-del="' + esc(a.id) + '" title="'+tr('删除','Delete')+'">🗑️</button></div></div>'; }).join('') + '</div>'; $('manager-search').oninput = function () { var q = this.value.toLowerCase(); c.querySelectorAll('.manager-item').forEach(function (el) { el.hidden = el.textContent.toLowerCase().indexOf(q) < 0; }); }; $('manager-add').onclick = function () { openForm(k, null); }; c.querySelectorAll('[data-edit]').forEach(function (b) { b.onclick = function () { openForm(k, m.items.find(function (a) { return a.id === b.dataset.edit; })); }; }); c.querySelectorAll('[data-fav]').forEach(function (b) { b.onclick = function () { var a = m.items.find(function (a) { return a.id === b.dataset.fav; }); a.favorite = !a.favorite; save(); renderManager(k); }; }); c.querySelectorAll('[data-del]').forEach(function (b) { b.onclick = function () { m.items = m.items.filter(function (a) { return a.id !== b.dataset.del; }); save(); renderManager(k); }; }); }
  function openDrawer(k) { moduleKey = k; $('drawer-title').textContent = isEn() ? (k === 'outing' ? 'Manage Places' : (k === 'chat' ? 'Manage Chat Cards' : 'Manage Activities')) : (k === 'outing' ? '管理地点库' : (k === 'chat' ? '管理聊天库' : '管理活动库')); $('drawer-backdrop').hidden = false; $('library-drawer').classList.add('open'); $('library-drawer').setAttribute('aria-hidden', 'false'); renderManager(k); setTimeout(function () { $('manager-search').focus(); }, 120); }
  function closeDrawer() { $('library-drawer').classList.remove('open'); $('library-drawer').setAttribute('aria-hidden', 'true'); setTimeout(function () { $('drawer-backdrop').hidden = true; }, 220); }
  function openForm(k, a) { $('item-module').value = k; $('item-id').value = a ? a.id : ''; $('modal-title').textContent = (a ? '编辑' : '新增') + (k === 'outing' ? '地点' : '内容'); $('item-name').value = a ? a.nameZh : ''; $('item-name-en').value = a ? a.nameEn || '' : ''; $('item-emoji').value = a ? a.emoji || '🎈' : '🎈'; $('item-desc').value = a ? a.descriptionZh || '' : ''; $('item-favorite').checked = !!(a && a.favorite); $('outing-fields').hidden = k !== 'outing'; var m = mod(k); $('item-category').innerHTML = m.categories.map(function (c) { return '<option value="' + c.id + '">' + c.emoji + ' ' + c.nameZh + '</option>'; }).join(''); $('item-category').value = a ? a.categoryId : m.categories[0].id; if (k === 'outing') { var map = {area:'area',region:'region',indoor:'indoorOutdoor',age:'suitableAge',duration:'duration',highlights:'highlights',notes:'notes',map:'mapSearchName'}; Object.keys(map).forEach(function (x) { $('item-' + x).value = a ? a[map[x]] || '' : ''; }); } $('item-modal').hidden = false; }
  function submitForm(e) { e.preventDefault(); var k = $('item-module').value, m = mod(k), id = $('item-id').value, a = id && m.items.find(function (x) { return x.id === id; }); var d = { nameZh: $('item-name').value.trim(), nameEn: $('item-name-en').value.trim() || $('item-name').value.trim(), categoryId: $('item-category').value, emoji: $('item-emoji').value || '🎈', descriptionZh: $('item-desc').value.trim(), descriptionEn: $('item-desc').value.trim(), favorite: $('item-favorite').checked, updatedAt: S.now() }; if (k === 'outing') { d.area = $('item-area').value.trim(); d.region = $('item-region').value; d.indoorOutdoor = $('item-indoor').value.trim(); d.suitableAge = $('item-age').value.trim(); d.duration = $('item-duration').value.trim(); d.highlights = $('item-highlights').value.trim(); d.notes = $('item-notes').value.trim(); d.mapSearchName = $('item-map').value.trim() || d.nameZh; } if (a) Object.assign(a, d); else { d.id = S.genId(); d.source = 'custom'; d.createdAt = S.now(); d.pickCount = 0; d.lastPickedAt = null; m.items.unshift(d); } save(); $('item-modal').hidden = true; renderManager(k); }
  function init() {
    var tips=['今天和孩子聊聊：如果你能设计一个秘密基地，会放在哪里？','小提示：先听完孩子的想法，再问一个“为什么”。','睡前可以问：今天哪一刻让你觉得自己很棒？']; var ti=0; setInterval(function(){var el=$('chat-tips');if(el)el.textContent='💡 '+tips[ti++%tips.length];},4200); var r = S.loadState(); state = r.state; showView('play'); document.querySelectorAll('.tab').forEach(function (b) { b.onclick = function () { showView(b.dataset.view); }; }); document.querySelectorAll('[data-manage]').forEach(function (b) { b.onclick = function () { openDrawer(b.dataset.manage); }; }); document.querySelectorAll('[data-toggle]').forEach(function (b) { b.onclick = function () { $(b.dataset.toggle).hidden = !$(b.dataset.toggle).hidden; }; }); $('play-pick').onclick = playPick; $('chat-pick').onclick = chatPick; $('chat-reroll').onclick = chatPick; $('chat-filter-toggle').onclick = function () { $('chat-filter-panel').hidden = !$('chat-filter-panel').hidden; }; $('outing-pick').onclick = outingPick; $('outing-filter-toggle').onclick = function () { $('outing-filter-panel').hidden = !$('outing-filter-panel').hidden; }; ['outing-indoor','outing-duration'].forEach(function (id) { $(id).onchange = updateSummaries; }); $('item-form').onsubmit = submitForm; $('drawer-close').onclick = closeDrawer; $('drawer-backdrop').onclick = closeDrawer; document.querySelectorAll('[data-close]').forEach(function (b) { b.onclick = function () { $(b.dataset.close).hidden = true; }; }); $('open-settings').onclick = function () { $('s-name').value = state.settings.userName; $('s-language').value = state.settings.language; $('settings-modal').hidden = false; }; $('save-settings').onclick = function () { state.settings.userName = $('s-name').value.trim() || '小朋友'; state.settings.language = $('s-language').value; save(); applyLanguage(); $('settings-modal').hidden = true; }; var installBtn=$('install-app'); if(installBtn){installBtn.onclick=function(){if(!installPrompt)return;installPrompt.prompt();installPrompt.userChoice.then(function(){installPrompt=null;installBtn.hidden=true;});};} window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();installPrompt=e;if(installBtn)installBtn.hidden=false;}); window.addEventListener('appinstalled',function(){installPrompt=null;if(installBtn)installBtn.hidden=true;}); if(location.protocol==='file:'&&$('install-note'))$('install-note').textContent='请通过 http:// 或 https:// 网址打开；直接打开本地文件无法安装。'; renderCategories('play','play-categories'); renderCategories('chat','chat-categories'); renderOutingFilters(); updateSummaries(); applyLanguage(); }
  init();
})();
