(function () {
  'use strict';
  // 内置“玩一玩”目录：一项一行，便于人工查看和维护。
  var catalog = [
    ['洪恩识字', 'Honso Literacy', 'learning', '📚', '打开洪恩识字，今天只认 1 个字，再让孩子当小老师讲给你听。', 'Open the literacy app, learn one character, then let your child teach it back.'],
    ['数学启蒙', 'Early Math', 'learning', '🔢', '用家里的积木或水果数到 10，再比一比哪一堆更多。', 'Count to 10 with blocks or fruit, then compare which pile has more.'],
    ['看布鲁伊动画片', 'Watch Bluey', 'learning', '📺', '看一集布鲁伊，看完只问一个问题：他们是怎么一起解决的？', 'Watch one Bluey episode, then ask how they solved it together.'],
    ['学习英语', 'Learn English', 'learning', '🗣️', '挑 3 个家里看得到的东西，用中文和英文各说一遍。', 'Pick three things you can see, and name each in Chinese and English.'],
    ['科普动画片', 'Science Cartoon', 'learning', '🔬', '看一集科普动画，看完让孩子用自己的话说一个新发现。', 'Watch one science cartoon, then retell one new discovery.'],
    ['磁力片搭城堡', 'Magnetic Castle', 'toy', '🏰', '用磁力片搭一座有门的城堡，搭完再决定谁住进去。', 'Build a castle with a door, then decide who lives inside.'],
    ['乐高搭动物乐园', 'LEGO Animal Park', 'toy', '🦁', '搭一只动物，给它起名字，再说说它吃什么。', 'Build an animal, name it, and say what it eats.'],
    ['拼图闯关', 'Puzzle Challenge', 'toy', '🧩', '选一副拼图，先找边角，拼完后指出最难的一块。', 'Do one puzzle. Find the edges first, then point out the hardest piece.'],
    ['积木搭小房子', 'Build a Little House', 'toy', '🧱', '搭一间小房子，要有门和一扇窗，再讲讲谁住在里面。', 'Build a little house with a door and a window, then say who lives there.'],
    ['三只小猪', 'The Three Little Pigs', 'toy', '🐷', '用积木或玩偶演一遍三只小猪，说说哪座房子最牢。', 'Act out The Three Little Pigs and decide which house is strongest.'],
    ['超级密码机', 'Super Code Machine', 'toy', '🔐', '把《超级密码机》拿出来玩一局，结束时说说哪条线索最有用。', 'Play one round of Super Code Machine and say which clue helped most.'],
    ['磁力块', 'Magnetic Blocks', 'toy', '🔷', '用磁力块搭一个今天想去的地方，让别人猜是哪里。', 'Build a place you want to visit and let someone guess what it is.'],
    ['飞行棋大战', 'Flying Chess', 'board', '🎲', '下完一局飞行棋。掷到后退时，说说还可以怎么办。', 'Play one game of flying chess. When you move back, talk about what else you could do.'],
    ['动物有钱', 'Animal Money', 'board', '🐘', '按盒子上的规则玩一局《动物有钱》，结束时讲讲你是怎么赢的或差在哪。', 'Play Animal Money by the box rules, then say how you won or what was missing.'],
    ['记忆翻牌配对', 'Memory Match', 'board', '🃏', '翻牌找相同的一对。可以先约定只翻 8 张，降低难度。', 'Match pairs by memory. Start with eight cards if that feels easier.'],
    ['熊猫餐厅', 'Panda Restaurant', 'board', '🐼', '按说明书玩一局《熊猫餐厅》，玩的时候让孩子负责给客人点单。', 'Play Panda Restaurant and let your child take the orders.'],
    ['长颈鹿围巾', 'Giraffe Scarf', 'board', '🦒', '按说明书玩一局《长颈鹿围巾》，看看谁先把围巾接对。', 'Play Giraffe Scarf and see who can match the scarf first.'],
    ['读中文绘本', 'Read a Chinese Picture Book', 'book', '📖', '读一本中文绘本，读完只问：你最喜欢哪一页？为什么？', 'Read one Chinese picture book, then ask which page they liked and why.'],
    ['读英文绘本', 'Read an English Picture Book', 'book', '📘', '读一本英文绘本，每页留一个词，让孩子指图再说一遍。', 'Read one English picture book and repeat one word on each page while pointing at the picture.'],
    ['纸盘做面具', 'Paper Plate Mask', 'craft', '🎭', '用纸盘做一个面具，戴上后用这个新身份说一句话。', 'Make a paper-plate mask, put it on, and say one line as that character.'],
    ['橡皮泥捏小动物', 'Clay Animals', 'craft', '🐣', '捏一只小动物，先捏身体，再加眼睛，最后给它找个家。', 'Shape a small animal: body first, then eyes, then find it a home.'],
    ['折纸飞机比赛', 'Paper Airplane Race', 'craft', '✈️', '每人折一架纸飞机，比谁飞得更远，再改一改机翼重试。', 'Fold one paper airplane each, see whose flies farther, then adjust the wings and try again.'],
    ['手工创作', 'Free Craft', 'craft', '✂️', '用桌上已有的纸、胶带或瓶子做一件小东西，做完给它起名。', 'Make something small from paper, tape, or a bottle already on the table, then name it.'],
    ['画一幅画', 'Draw a Picture', 'craft', '🎨', '画今天最想记住的一件事，画完讲给对方听。', 'Draw the moment from today you most want to remember, then tell the story.'],
    ['客厅音乐会', 'Living Room Concert', 'role', '🎤', '开一场三分钟客厅音乐会，可以用唱歌、拍手或锅碗。', 'Hold a three-minute living-room concert with singing, clapping, or pots.'],
    ['医生游戏', 'Doctor Game', 'role', '🩺', '玩医生游戏：先问哪里不舒服，再轻轻检查，最后给一个小建议。', 'Play doctor: ask what hurts, check gently, then give one small suggestion.'],
    ['蹦床', 'Trampoline', 'fitness', '🤸', '大人在旁边看着，跳 20 下。可以边跳边数，累了就停。', 'With an adult watching, do 20 jumps. Count out loud and stop when tired.'],
    ['吊单杠', 'Bar Hang', 'fitness', '🧗', '大人在旁边保护，挂在单杠上试试，下来后说说手臂什么感觉。', 'Hang from the bar with an adult spotting you, then say how your arms feel.'],
    ['仰卧起坐', 'Sit-Ups', 'fitness', '💪', '做 8 个仰卧起坐就够了。大人可以按住脚，做完休息喝水。', 'Do eight sit-ups. An adult can hold your feet, then rest and drink some water.'],
    ['旱地自由泳', 'Dry-Land Freestyle', 'fitness', '🏊', '躺在地板上做 10 次自由泳划手，看看谁的动作更像在水里。', 'Lie on the floor and do 10 freestyle strokes. See whose arms look most like swimming.'],
    ['厨房认字', 'Kitchen Words', 'learning', '🥫', '在食物包装上找 1 个今天要认的字，找到后用它说一句话。', 'Find one character on a food package and use it in a sentence.'],
    ['影子变变变', 'Moving Shadows', 'learning', '🌤️', '在阳光或灯光下看影子，过十分钟再看它有没有变长。', 'Look at a shadow in sunlight or lamplight, then check ten minutes later whether it changed.'],
    ['两堆比一比', 'Two Piles', 'learning', '🧺', '把玩具分成两堆，比哪堆更多、哪堆更大，再说说你的分法。', 'Split toys into two piles, compare which has more, and explain your rule.'],
    ['闭眼摸一摸', 'Mystery Touch', 'learning', '👐', '把一样小东西放进布袋，只靠摸猜它是什么，再说出两条线索。', 'Hide a small object in a cloth bag, guess it by touch, and name two clues.'],
    ['天气小记录', 'Weather Note', 'learning', '🌦️', '看一眼窗外，用一句话记下天气，再画一个对应的符号。', 'Look outside, describe the weather in one sentence, and draw a symbol for it.'],
    ['玩偶过家家', 'Doll House', 'toy', '🏡', '让玩偶过一个早晨：起床、吃饭、出门，每一步由孩子安排。', 'Give the dolls a morning: waking, eating, and going out, with your child directing each step.'],
    ['小车铺路', 'Car Road', 'toy', '🚗', '用书或纸箱搭一条路，让小车从家里开到一个“商店”。', 'Build a road with books or boxes and drive a car from home to a shop.'],
    ['骰子编故事', 'Dice Story', 'board', '🎲', '掷两次骰子：第一次决定有几只动物，第二次决定它们去哪里。', 'Roll twice: the first roll chooses how many animals, the second chooses where they go.'],
    ['给绘本配音', 'Book Voices', 'book', '🎙️', '读一本绘本时，每个人负责一个角色的声音，读完交换。', 'While reading a picture book, each person voices one character, then switch.'],
    ['封面猜故事', 'Cover Guess', 'book', '🔍', '先只看封面，猜三个可能发生的事，读完再看猜中了没有。', 'Look only at the cover, guess three things that might happen, then check after reading.'],
    ['睡前接一句', 'One More Line', 'book', '🌙', '你说一句故事开头，孩子接一句，来回四次后一起收尾。', 'You say a story opening, your child adds a line, and after four turns end it together.'],
    ['袜子木偶', 'Sock Puppet', 'craft', '🧦', '用一只干净袜子和纸眼睛做一个木偶，让它自我介绍。', 'Make a puppet from a clean sock and paper eyes, then let it introduce itself.'],
    ['树叶拓印', 'Leaf Rubbing', 'craft', '🍃', '把树叶放在纸下，用蜡笔轻轻涂，看看叶脉显出来没有。', 'Place a leaf under paper and rub gently with a crayon until the veins appear.'],
    ['纸条书签', 'Paper Bookmark', 'craft', '🔖', '剪一条纸做书签，写上今天想记住的一个词。', 'Cut a paper bookmark and write one word you want to remember today.'],
    ['水瓶小乐队', 'Bottle Band', 'craft', '🎵', '在几个杯子里装不同高度的水，轻轻敲一敲，比比声音。', 'Fill cups with different amounts of water, tap them gently, and compare the sounds.'],
    ['小小厨师', 'Little Chef', 'role', '👩‍🍳', '一起洗一种水果或摆盘，孩子负责决定摆成什么形状。', 'Wash one fruit or arrange a plate together, and let your child choose the shape.'],
    ['超市收银', 'Shop Checkout', 'role', '🧾', '用家里的零食当商品，一个当店员扫码，一个当顾客付钱。', 'Use snacks as goods: one person scans, the other pays.'],
    ['客厅寻宝', 'Living-Room Hunt', 'role', '🗺️', '藏三样小东西，每样配一句线索，找到后放回原处。', 'Hide three small things, give one clue each, and put them back afterward.'],
    ['宇航员着陆', 'Astronaut Landing', 'role', '🚀', '用沙发当地球，用靠垫当月球，演一段慢慢着陆。', 'Use the sofa as Earth and cushions as the Moon, and act out a slow landing.'],
    ['动物模仿操', 'Animal Moves', 'fitness', '🐸', '模仿青蛙跳、螃蟹走、小鸟飞各 5 次，累了就换成慢动作。', 'Do five frog jumps, crab walks, and bird flaps. Switch to slow motion if tired.'],
    ['胶带平衡木', 'Tape Beam', 'fitness', '🤸', '在地上贴一条胶带当平衡木，慢慢走过去，大人在旁边看着。', 'Stick a line of tape on the floor and walk it slowly, with an adult beside you.'],
    ['枕头障碍赛', 'Pillow Course', 'fitness', '🛋️', '用枕头摆三个小障碍，规定只能走、爬或跳，各过一遍。', 'Make three pillow obstacles and cross them once each by walking, crawling, or jumping.'],
    ['毛巾轻轻拉', 'Towel Pull', 'fitness', '🏳️', '两人各拉毛巾一头，约定用很小的力，坚持 5 秒就停。', 'Each person holds one end of a towel, pull gently, and stop after five seconds.']
  ].map(function (r) {
    return { id: 'play-' + r[0], nameZh: r[0], nameEn: r[1], categoryId: r[2], emoji: r[3],
      descriptionZh: r[4], descriptionEn: r[5], source: 'builtin' };
  });
  window.GamePicker = window.GamePicker || {};
  window.GamePicker.playCatalog = catalog;
})();
