(function () {
  'use strict';
  var NS = window.GamePicker = window.GamePicker || {};
  var KEY = 'gamepicker.v2';
  var PLAY_CATEGORIES = [['learning','学习','Learning','📚','#A8E6CF'],['toy','玩具','Toys','🧱','#FFB6A3'],['board','桌游','Board Games','🎲','#FFD98E'],['book','绘本','Picture Books','📖','#B8D8BA'],['craft','手工','Crafts','🎨','#C3B1E1'],['role','角色游戏','Role Play','🩺','#F6C1C7'],['fitness','运动','Fitness','💪','#A0D8EF']];
  var CHAT_CATEGORIES = [['daily','日常分享','Daily','🌤️','#FFD98E'],['feelings','感受与情绪','Feelings','🌼','#FFB6A3'],['family','家庭','Family','🏠','#A8E6CF'],['imagine','想象','Imagination','🧚','#C3B1E1'],['logic','逻辑思考','Thinking','🧠','#A0D8EF'],['bedtime','睡前','Bedtime','🌙','#B8D8BA'],['dreams','梦想','Dreams','🌈','#F6C1C7'],['reflect','复盘','Reflection','🔁','#E8C4A0'],['science','小小科普','Little Science','🔬','#A0D8EF']];
  var OUTING_CATEGORIES = [['indoor-park','室内公园','Indoor Park','🛝','#A8E6CF'],['theme-park','主题乐园','Theme Park','🎢','#FFB6A3'],['mall','商场亲子空间','Mall Family Space','🛍️','#FFD98E'],['cycling','骑行','Cycling','🚲','#A0D8EF'],['hiking','爬山与自然','Hiking & Nature','🥾','#B8D8BA'],['museum','博物馆/科技馆','Museum & Science','🔭','#C3B1E1'],['rainy','雨天备选','Rainy Day','☔','#F6C1C7'],['nearby','周边周末','Nearby Weekend','🧭','#E8C4A0']];
  function now(){return Date.now();} function genId(){return now().toString(36)+'-'+Math.random().toString(36).slice(2,8);} function cats(rows){return rows.map(function(r){return {id:r[0],nameZh:r[1],nameEn:r[2],emoji:r[3],color:r[4]};});}
  function item(o){return Object.assign({id:genId(),nameZh:'未命名',nameEn:'Untitled',categoryId:'other',emoji:'🎈',descriptionZh:'',descriptionEn:'',favorite:false,source:'custom',createdAt:now(),updatedAt:now(),pickCount:0,lastPickedAt:null},o);}
  function playSeed(){var a=function(n,c,e,d){return item({id:'play-'+n,nameZh:n,nameEn:e,categoryId:c,emoji:d,descriptionZh:'和家人一起完成一个小挑战，玩完后分享你的发现。',descriptionEn:'Try a small challenge together and share what you discovered.',source:'builtin'});};return [a('磁力片搭城堡','toy','Magnetic Castle','🏰'),a('读中文绘本','book','Read a Picture Book','📖'),a('纸盘做面具','craft','Paper Plate Mask','🎭'),a('客厅音乐会','role','Living Room Concert','🎤'),a('拼图闯关','board','Puzzle Challenge','🧩'),a('蹦床','fitness','Trampoline','🤸'),a('数学启蒙','learning','Early Math','🔢')];}
  function legacyPlaySeed(){var rows=[['洪恩识字','learning','📚'],['看布鲁伊动画片','learning','📺'],['学习英语','learning','🗣️'],['科普动画片','learning','🔬'],['乐高搭动物乐园','toy','🦁'],['积木搭小房子','toy','🧱'],['三只小猪','toy','🐷'],['超级密码机','toy','🔐'],['磁力块','toy','🔷'],['飞行棋大战','board','🎲'],['动物有钱','board','🐘'],['记忆翻牌配对','board','🃏'],['熊猫餐厅','board','🐼'],['长颈鹿围巾','board','🦒'],['读英文绘本','book','📘'],['橡皮泥捏小动物','craft','🐣'],['折纸飞机比赛','craft','✈️'],['手工创作','craft','✂️'],['画一幅画','craft','🎨'],['医生游戏','role','🩺'],['吊单杠','fitness','🧗'],['仰卧起坐','fitness','💪'],['旱地自由泳','fitness','🏊']];return rows.map(function(r){return item({id:'play-'+r[0],nameZh:r[0],nameEn:r[0],categoryId:r[1],emoji:r[2],descriptionZh:'和家人一起完成一个小挑战，玩完后分享你的发现。',descriptionEn:'Try a small challenge together and share what you discovered.',source:'builtin'});});}
  function mergePlaySeeds(items){var seen={};(items||[]).forEach(function(a){seen[a.nameZh]=true;});return (items||[]).concat(legacyPlaySeed().filter(function(a){return !seen[a.nameZh];}));}
  function outingSeed(){var a=function(name,area,cat,io,dur,high,notes){return item({id:'outing-'+name,nameZh:name,nameEn:name,area:area,region:area==='深圳市内'?'深圳市内':'深圳周边',categoryId:cat,emoji:cat==='cycling'?'🚲':cat==='hiking'?'🥾':cat==='museum'?'🔭':cat==='mall'?'🛍️':cat==='theme-park'?'🎢':cat==='rainy'?'☔':'🧭',indoorOutdoor:io,suitableAge:'3–12岁',duration:dur,highlights:high,notes:notes,mapSearchName:name,descriptionZh:high,descriptionEn:high,source:'builtin'});};var base=[a('深圳湾公园','深圳市内','cycling','室外','2–3小时','沿海骑行、看日落、亲子散步','注意防晒与补水'),a('莲花山公园','深圳市内','hiking','室外','2小时','登顶俯瞰城市，适合轻量爬山','周末建议早出发'),a('深圳市儿童乐园','深圳市内','theme-park','室外','半天','经典游乐设施，适合低龄儿童','关注现场开放项目'),a('深圳科学馆','深圳市内','museum','室内','2–3小时','互动展项和科学实验，雨天友好','提前查看展览安排'),a('欢乐海岸购物中心','深圳市内','mall','室内/室外','半天','商场亲子空间、餐饮与水岸散步','可按家庭预算灵活安排'),a('大鹏所城与较场尾','深圳市内','hiking','室外','一天','古城、人文和海边组合','建议安排往返交通'),a('惠州西湖','深圳周边','nearby','室外','一天','湖边散步、骑行和城市周末游','适合自驾或高铁接驳'),a('东莞松山湖','深圳周边','cycling','室外','一天','环湖骑行、草地和亲子休闲','可自带儿童自行车'),a('珠海长隆海洋王国','深圳周边','theme-park','室内/室外','1–2天','大型海洋主题乐园，适合周末旅行','提前规划住宿与门票')];var extra=(NS.outingExtra||[]).map(function(x){return item(Object.assign({source:'builtin',emoji:'🧭',descriptionZh:x.highlights||x.nameZh,descriptionEn:x.highlights||x.nameZh},x));});var seen={};return base.concat(extra).filter(function(x){if(seen[x.region+'|'+x.nameZh])return false;seen[x.region+'|'+x.nameZh]=true;return true;});}
  function chatSeed(){var topics=(NS.chat&&NS.chat.topics)||[];return topics.map(function(t){return item({id:'chat-'+t.id,nameZh:t.promptZh||t.questionZh||'聊天话题',nameEn:t.promptEn||t.questionEn||'Chat topic',categoryId:t.categoryId||'daily',emoji:t.emoji||'💬',descriptionZh:t.promptZh||t.questionZh||'',descriptionEn:t.promptEn||t.questionEn||'',promptZh:t.promptZh||t.questionZh||'',promptEn:t.promptEn||t.questionEn||'',followUpsZh:t.followUpsZh||[],followUpsEn:t.followUpsEn||[],factZh:t.factZh||'',factEn:t.factEn||'',hintZh:t.hintZh||'',hintEn:t.hintEn||'',answerZh:t.answerZh||'',answerEn:t.answerEn||'',difficulty:t.difficulty||1,source:'builtin'});});}
  function defaultState(){var legacy=mergePlaySeeds(playSeed());return {schemaVersion:2,settings:{userName:'小朋友',language:'zh-CN'},modules:{play:{categories:cats(PLAY_CATEGORIES),items:legacy.length?legacy:[],lastPickedId:null},chat:{categories:cats(CHAT_CATEGORIES),items:chatSeed(),lastPickedId:null},outing:{categories:cats(OUTING_CATEGORIES),items:outingSeed(),lastPickedId:null}}};}
  function normalizeState(data){data=data&&typeof data==='object'?data:{};if(data.schemaVersion===2&&data.modules){data.modules.play.items=mergePlaySeeds(data.modules.play.items||[]);Object.keys(data.modules).forEach(function(k){(data.modules[k].items||[]).forEach(function(a){delete a.budget;});});delete data.settings.voiceEnabled;var existing={};(data.modules.outing.items||[]).forEach(function(a){existing[a.region+'|'+a.nameZh]=true;});(NS.outingExtra||[]).forEach(function(x){if(!existing[x.region+'|'+x.nameZh]){data.modules.outing.items.push(item(Object.assign({source:'builtin',emoji:'🧭',descriptionZh:x.highlights||x.nameZh,descriptionEn:x.highlights||x.nameZh},x)));}});return data;}var fresh=defaultState(),old=Array.isArray(data.activities)?data.activities:[],map={game:'role',outdoor:'fitness',other:'role'};if(old.length)fresh.modules.play.items=mergePlaySeeds(old.map(function(a){var copy=item(a);delete copy.budget;copy.categoryId=map[copy.categoryId]||copy.categoryId;return copy;}));if(data.settings){fresh.settings.userName=data.settings.userName||'小朋友';fresh.settings.language=data.settings.language==='en-US'?'en-US':'zh-CN';}return fresh;}
  function storageAvailable(){try{var k='__explore__';localStorage.setItem(k,'1');localStorage.removeItem(k);return true;}catch(e){return false;}} function saveState(s){if(!storageAvailable())return false;try{localStorage.setItem(KEY,JSON.stringify(s));return true;}catch(e){return false;}}
  function loadState(){if(!storageAvailable())return {state:defaultState(),inMemory:true,corrupt:false};var raw=localStorage.getItem(KEY),legacy=localStorage.getItem('gamepicker.v1');if(!raw&&legacy){try{var migrated=normalizeState(JSON.parse(legacy));saveState(migrated);return {state:migrated,inMemory:false,corrupt:false};}catch(e){}}if(!raw){var s=defaultState();saveState(s);return {state:s,inMemory:false,corrupt:false};}try{var parsed=JSON.parse(raw);if(legacy&&parsed&&parsed.modules&&parsed.modules.play){try{var old=JSON.parse(legacy);if(Array.isArray(old.activities))parsed.modules.play.items=(parsed.modules.play.items||[]).concat(old.activities);}catch(ignore){}}var normalized=normalizeState(parsed);saveState(normalized);return {state:normalized,inMemory:false,corrupt:false};}catch(e2){var f=defaultState();saveState(f);return {state:f,inMemory:false,corrupt:true};}}
  NS.storage={KEY:KEY,defaultState:defaultState,normalizeState:normalizeState,saveState:saveState,loadState:loadState,now:now,genId:genId,PLAY_CATEGORIES:PLAY_CATEGORIES,CHAT_CATEGORIES:CHAT_CATEGORIES,OUTING_CATEGORIES:OUTING_CATEGORIES};
})();
