(function () {
  'use strict';
  var NS = window.GamePicker = window.GamePicker || {};
  var KEY = 'explorekids.state.v1';
  var PLAY_CATEGORIES = [['learning','学习','Learning','📚','#A8E6CF'],['toy','玩具','Toys','🧱','#FFB6A3'],['board','桌游','Board Games','🎲','#FFD98E'],['book','绘本','Picture Books','📖','#B8D8BA'],['craft','手工','Crafts','🎨','#C3B1E1'],['role','角色游戏','Role Play','🩺','#F6C1C7'],['fitness','运动','Fitness','💪','#A0D8EF']];
  var CHAT_CATEGORIES = [['daily','日常分享','Daily','🌤️','#FFD98E'],['feelings','感受与情绪','Feelings','🌼','#FFB6A3'],['family','家庭','Family','🏠','#A8E6CF'],['imagine','想象','Imagination','🧚','#C3B1E1'],['logic','逻辑思考','Thinking','🧠','#A0D8EF'],['bedtime','睡前','Bedtime','🌙','#B8D8BA'],['dreams','梦想','Dreams','🌈','#F6C1C7'],['reflect','复盘','Reflection','🔁','#E8C4A0'],['science','小小科普','Little Science','🔬','#A0D8EF']];
  var OUTING_CATEGORIES = [['indoor-park','室内公园','Indoor Park','🛝','#A8E6CF'],['theme-park','主题乐园','Theme Park','🎢','#FFB6A3'],['mall','商场亲子空间','Mall Family Space','🛍️','#FFD98E'],['cycling','骑行','Cycling','🚲','#A0D8EF'],['hiking','爬山与自然','Hiking & Nature','🥾','#B8D8BA'],['museum','博物馆/科技馆','Museum & Science','🔭','#C3B1E1'],['rainy','雨天备选','Rainy Day','☔','#F6C1C7'],['nearby','周边周末','Nearby Weekend','🧭','#E8C4A0']];
  function now(){return Date.now();} function genId(){return now().toString(36)+'-'+Math.random().toString(36).slice(2,8);} function cats(rows){return rows.map(function(r){return {id:r[0],nameZh:r[1],nameEn:r[2],emoji:r[3],color:r[4]};});}
  function item(o){return Object.assign({id:genId(),nameZh:'未命名',nameEn:'Untitled',categoryId:'other',emoji:'🎈',descriptionZh:'',descriptionEn:'',favorite:false,source:'custom',createdAt:now(),updatedAt:now(),pickCount:0,lastPickedAt:null},o||{});}
  function playSeed(){return (NS.playCatalog||[]).map(function(x){return item(x);});}
  function outingSeed(){var a=function(name,area,cat,io,dur,high,notes){return item({id:'outing-'+name,nameZh:name,nameEn:name,area:area,region:area==='深圳市内'?'深圳市内':'深圳周边',categoryId:cat,emoji:cat==='cycling'?'🚲':cat==='hiking'?'🥾':cat==='museum'?'🔭':cat==='mall'?'🛍️':cat==='theme-park'?'🎢':cat==='rainy'?'☔':'🧭',indoorOutdoor:io,suitableAge:'3–12岁',duration:dur,highlights:high,notes:notes,mapSearchName:name,descriptionZh:high,descriptionEn:high,source:'builtin'});};var base=[a('深圳湾公园','深圳市内','cycling','室外','2–3小时','沿海骑行、看日落、亲子散步','注意防晒与补水'),a('莲花山公园','深圳市内','hiking','室外','2小时','登顶俯瞰城市，适合轻量爬山','周末建议早出发'),a('深圳市儿童乐园','深圳市内','theme-park','室外','半天','经典游乐设施，适合低龄儿童','关注现场开放项目'),a('深圳科学馆','深圳市内','museum','室内','2–3小时','互动展项和科学实验，雨天友好','提前查看展览安排'),a('欢乐海岸购物中心','深圳市内','mall','室内/室外','半天','商场亲子空间、餐饮与水岸散步','可按家庭预算灵活安排'),a('大鹏所城与较场尾','深圳市内','hiking','室外','一天','古城、人文和海边组合','建议安排往返交通'),a('惠州西湖','深圳周边','nearby','室外','一天','湖边散步、骑行和城市周末游','适合自驾或高铁接驳'),a('东莞松山湖','深圳周边','cycling','室外','一天','环湖骑行、草地和亲子休闲','可自带儿童自行车'),a('珠海长隆海洋王国','深圳周边','theme-park','室内/室外','1–2天','大型海洋主题乐园，适合周末旅行','提前规划住宿与门票')];var extra=(NS.outingExtra||[]).map(function(x){return item(Object.assign({source:'builtin',emoji:'🧭',descriptionZh:x.highlights||x.nameZh,descriptionEn:x.highlights||x.nameZh},x));});var seen={};return base.concat(extra).filter(function(x){if(seen[x.region+'|'+x.nameZh])return false;seen[x.region+'|'+x.nameZh]=true;return true;});}
  function chatSeed(){var topics=(NS.chat&&NS.chat.topics)||[];return topics.map(function(t){return item({id:'chat-'+t.id,nameZh:t.promptZh||t.questionZh||'聊天话题',nameEn:t.promptEn||t.questionEn||'Chat topic',categoryId:t.categoryId||'daily',emoji:t.emoji||'💬',descriptionZh:t.promptZh||t.questionZh||'',descriptionEn:t.promptEn||t.questionEn||'',promptZh:t.promptZh||t.questionZh||'',promptEn:t.promptEn||t.questionEn||'',followUpsZh:t.followUpsZh||[],followUpsEn:t.followUpsEn||[],factZh:t.factZh||'',factEn:t.factEn||'',hintZh:t.hintZh||'',hintEn:t.hintEn||'',answerZh:t.answerZh||'',answerEn:t.answerEn||'',difficulty:t.difficulty||1,source:'builtin'});});}
  function baseState(){return {schemaVersion:1,settings:{userName:'小朋友',language:'zh-CN'},modules:{play:{categories:cats(PLAY_CATEGORIES),items:playSeed(),lastPickedId:null},chat:{categories:cats(CHAT_CATEGORIES),items:chatSeed(),lastPickedId:null},outing:{categories:cats(OUTING_CATEGORIES),items:outingSeed(),lastPickedId:null}}};}
  function clone(x){return JSON.parse(JSON.stringify(x));} function same(a,b){return JSON.stringify(a)===JSON.stringify(b);}
  function catalog(k){return baseState().modules[k].items;}
  function deltaFromState(s){var out={schemaVersion:1,settings:clone(s.settings||{}),modules:{}};['play','chat','outing'].forEach(function(k){var base=catalog(k), by={};base.forEach(function(x){by[x.id]=x;});var m=s.modules[k], d={customItems:[],overrides:{},deletedBuiltinIds:[],favorites:{},stats:{},lastPickedId:m.lastPickedId||null};(m.items||[]).forEach(function(x){var b=by[x.id];if(!b||x.source==='custom'){d.customItems.push(clone(x));return;}var patch={};Object.keys(x).forEach(function(key){if(['id','source','createdAt','updatedAt','favorite','pickCount','lastPickedAt'].indexOf(key)<0&&!same(x[key],b[key]))patch[key]=clone(x[key]);});if(Object.keys(patch).length)d.overrides[x.id]=patch;if(x.favorite)d.favorites[x.id]=true;if(x.pickCount||x.lastPickedAt)d.stats[x.id]={pickCount:x.pickCount||0,lastPickedAt:x.lastPickedAt||null};});var present={};(m.items||[]).forEach(function(x){present[x.id]=true;});base.forEach(function(x){if(!present[x.id])d.deletedBuiltinIds.push(x.id);});out.modules[k]=d;});return out;}
  function fullFromDelta(d){var s=baseState();s.settings=Object.assign(s.settings,d.settings||{});['play','chat','outing'].forEach(function(k){var m=s.modules[k], x=d.modules&&d.modules[k]||{}, deleted={};(x.deletedBuiltinIds||[]).forEach(function(id){deleted[id]=true;});m.items=m.items.filter(function(a){return !deleted[a.id];});Object.keys(x.overrides||{}).forEach(function(id){var a=m.items.find(function(z){return z.id===id;});if(a)Object.assign(a,x.overrides[id]);});(x.customItems||[]).forEach(function(a){m.items.push(item(a));});Object.keys(x.favorites||{}).forEach(function(id){var a=m.items.find(function(z){return z.id===id;});if(a)a.favorite=true;});Object.keys(x.stats||{}).forEach(function(id){var a=m.items.find(function(z){return z.id===id;});if(a)Object.assign(a,x.stats[id]);});m.lastPickedId=x.lastPickedId||null;});return s;}
  function storageAvailable(){try{var k='__explorekids__';localStorage.setItem(k,'1');localStorage.removeItem(k);return true;}catch(e){return false;}}
  function saveState(s){if(!storageAvailable())return false;try{localStorage.setItem(KEY,JSON.stringify(deltaFromState(s)));return true;}catch(e){return false;}}
  function loadState(){if(!storageAvailable())return {state:baseState(),inMemory:true,corrupt:false};var raw=localStorage.getItem(KEY);if(!raw){var fresh=baseState();saveState(fresh);return {state:fresh,inMemory:false,corrupt:false};}try{var parsed=JSON.parse(raw);if(!parsed||parsed.schemaVersion!==1)throw new Error('invalid state');return {state:fullFromDelta(parsed),inMemory:false,corrupt:false};}catch(e){var fallback=baseState();saveState(fallback);return {state:fallback,inMemory:false,corrupt:true};}}
  NS.storage={KEY:KEY,defaultState:baseState,saveState:saveState,loadState:loadState,now:now,genId:genId,PLAY_CATEGORIES:PLAY_CATEGORIES,CHAT_CATEGORIES:CHAT_CATEGORIES,OUTING_CATEGORIES:OUTING_CATEGORIES};
})();
